### ISSUE TITLE
Build arm64 binary for Apple Silicon (M1/M2) Macs

### ISSUE THREAD

**Issue by jarp0l** [cado-security/cloudgrep#16]
Although there is [`generate_osx_binary.sh`](https://github.com/cado-security/cloudgrep/blob/main/release/generate_osx_binary.sh) script to build universal binary for both macOS x86_64 and arm64, the [CI uses](https://github.com/cado-security/cloudgrep/blob/main/.github/workflows/app-ci.yml#L98) [`generate_linux_binary.sh`](https://github.com/cado-security/cloudgrep/blob/main/release/generate_linux_binary.sh) instead. Since there is no target arch in `generate_linux_binary.sh`, the CI ends up generating x86_64 binary according to the arch of the underlying system, which in this case is macOS-12 x86_64 (see the most recent [run](https://github.com/cado-security/cloudgrep/actions/runs/6746384173/job/18340194917#step:5:132)). I'm not sure whether this was intentional.

```bash
$ file cloudgrep
cloudgrep: Mach-O 64-bit executable x86_64
```

When I try to run `cloudgrep` binary in my M1 mac, it doesn't output anything; not even `cloudgrep -h` prints help.

We can either build two separate binaries for each arch and release separately named as something like `dist-osx-x86_64.zip`/`dist-osx-amd64.zip` and `dist-osx-arm64.zip` (though this is a secondary concern), or build a universal binary to cover both archs.

Relevant discussion: [How to compile on MacOS for x86, M1 and M2 (apple silicon) #7703](https://github.com/orgs/pyinstaller/discussions/7703)

**Comment by jarp0l** [comment]
After several changes here and there I was able to build a working binary for x86-64 arch, which also worked in my M1 mac. Here are the build artifacts for linux and macOS if anybody wants to test: https://github.com/jarp0l/cloudgrep/actions/runs/6834079982#artifacts (haven't made any changes for windows).
I'm working on this branch: https://github.com/jarp0l/cloudgrep/tree/arm64-macos-binary

### Changes:

`cloudgrep/__main__.py`:
```
- from .cloudgrep import CloudGrep
+ from cloudgrep.cloudgrep import CloudGrep
```

`release/generate_linux_binary.sh`:
```
- pyinstaller  --onefile --clean ./cloudgrep/cloudgrep.py
+ pyinstaller  --onefile --name cloudgrep --clean ./cloudgrep/__main__.py
```

`.github/workflows/app-ci.yml`:
(`compile-linux` and `compile-macos` jobs)
```
- ./dist/cloudgrep # check it doesn't return non 0 exit status, i.e. crash
+ ./dist/cloudgrep -h # check it doesn't return non 0 exit status, i.e. crash
```

---

But the binary is too slow though. I think it's due to PyInstaller.
```sh
$ time ./cloudgrep -h
# ...<snip>...
./cloudgrep -h  0.80s user 0.57s system 4% cpu 29.153 total
```

```sh
$ time ./cloudgrep -h
# ...<snip>...
./cloudgrep -h  0.77s user 0.56s system 9% cpu 14.593 total
```

My system specs:
```sh
$ system_profiler SPSoftwareDataType SPHardwareDataType
Software:
    System Software Overview:
      System Version: macOS 14.1
      Kernel Version: Darwin 23.1.0
      # ...<snip>...

Hardware:
    Hardware Overview:
      # ...<snip>...
      Chip: Apple M1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      # ...<snip>...
```

**Comment by chrisdoman** [comment]
Thank-you for sharing! Will review the changes in your branch and test on the mac 👍

**Comment by chrisdoman** [comment]
Thank-you for the fix!
Merged in https://github.com/cado-security/cloudgrep/pull/17

ooks like the performance difference is mostly the one-off cost for pyinstaller extracting to /tmp

python3 cloudgrep.py -b bucket -q error --debug 2.71s user 0.62s system 37% cpu 8.802 total
./cloudgrep -b bucket -q error --debug 2.50s user 1.01s system 29% cpu 11.877 total

**Comment by jarp0l** [comment]
Ahh, that's okay then.

I have opened PR https://github.com/cado-security/cloudgrep/pull/19 that fixes PyInstaller command for Windows binary as well.

**Comment by chrisdoman** [comment]
Great - thankyou
