### ISSUE TITLE
How to install globally?

### ISSUE THREAD

**Issue by toloco** [cado-security/cloudgrep#2]
As a user, I would like to run the command globally without using the full path.

E.g.

```bash
cloudgrep --bucket test-s3-access-logs --query 9RXXKPREHHTFQD77
```

Why:
Well this tool can be used by users to integrate with bigger scripts.

**Comment by toloco** [comment]
If you need help with that I could help.

**Comment by chrisdoman** [comment]
Hi @toloco sure please feel free to send over a PR.

If you're on Linux/OSX I'd just use an alias for now, i.e.
alias cloudgrep="python3 /home/cloudgrep.py"

**Comment by chrisdoman** [comment]
Note you can now also run as an uncompiled binary which may make this easier
https://github.com/cado-security/cloudgrep/releases/tag/Latest

**Comment by toloco** [comment]
@chrisdoman thanks for answering!,

I suggest using something like entry points/console scripts from setup.py.
https://packaging.python.org/en/latest/specifications/entry-points/

That way you get a well-rounded application, that can be set up using standard tools like Pypi and gives you the alias in one go.

See how pytest guys are going it here: https://github.com/pytest-dev/pytest/blob/main/setup.cfg#L63.

**Comment by chrisdoman** [comment]
I've merged in your PR now along with the test fixes. Thank-you!

**Comment by toloco** [comment]
sure!

Happy its better
