### ISSUE TITLE
Unable to pass custom endpoint_url

### ISSUE THREAD

**Issue by igrikus** [cado-security/cloudgrep#26]
None of the `endpoint` parameters (set with profile or env) are used when using custom s3 storage.

Boto3 ignores this when creating Session(). This is [fixed after 1.28.0.](https://github.com/boto/boto3/pull/2746#issuecomment-1626113796)

I updated the requirements.txt locally:
```
botocore>=1.24.46
boto3>=1.28.0
boto3-stubs>=1.20.49
```
And now it works fine

Could you please update the `boto3` package?

**Comment by chrisdoman** [comment]
Thanks! Will bump now
