### ISSUE TITLE
macOS Install Error: YARA-Python 4.3.1

### ISSUE THREAD

**Issue by Andi-A** [cado-security/cloudgrep#28]
Encountering an error on macOS platform when attempting to download the YARA-Python library, specifically version 4.3.1. This issue disrupts the installation process for requirements and results in a critical failure, preventing the tool from being executed.

**Error Message:**
      Building wheels for collected packages: yara-python
      Building wheel for yara-python (setup.py) ... error
      error: subprocess-exited-with-error
      python setup.py bdist_wheel did not run successfully.
      │ exit code: 1
      ╰─> [227 lines of output]
          /opt/homebrew/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`

**Environment Information:**
      macOS version: `Sonoma 14`
      Python version: `Python 3.11.6`
      Homebrew version: `Homebrew 4.2.0`

**Comment by chrisdoman** [comment]
Hi @Andi-A sorry for the delay. I've changed the yara depenency, so if you pull the latest code it should work for you now. Please let me know if you have any issues.

**Comment by Andi-A** [comment]
Hey @chrisdoman, it's working just fine now. Thanks for helping out, appreciated it very much!
