### ISSUE TITLE
Pypi publication

### ISSUE THREAD

**Issue by toloco** [cado-security/cloudgrep#3]
As a user, I would rather install the app using global pypi.

Tasks:
- Make the app installable
- Publish app to pypi
- CI/CD(publishing)

**Comment by chrisdoman** [comment]
Hi @toloco Sure - Is the use case here to be able to import it into other python scripts?
Not to hard to publish to pypi, I can copy over an action from another repo.

**Comment by chrisdoman** [comment]
Hi @toloco - Now available at https://pypi.org/project/cloudgrep/1.0.5/ :)

**Comment by toloco** [comment]
nice one!!!
