### ISSUE TITLE
Cloudgrep downloading files not working on Windows 11

### ISSUE THREAD

**Issue by rafal-dudek** [cado-security/cloudgrep#30]
When using cloudgrep on Windows 11, it finds files on Google Storage bucket but does not find any result.
I am using command `cloudgrep.py -gb bucket_name_12345 -q LoggingIntegrationBatchingTest -hf -lf json -d`

Looks like in cloudgrep  downloading files from Google Storage is not working for Windows 11:
https://github.com/cado-security/cloudgrep/blob/main/cloudgrep/cloud.py#L129 - This method creates and opens temp file.
https://github.com/cado-security/cloudgrep/blob/main/cloudgrep/cloud.py#L132 - Then, this method cannot save the blob, because file is already opened. If I debug the code, I get exception `[Errno 13] Permission denied: C:\\Users\\...\\AppData\\Local\\Temp\\8\\tmp8chhli1l'`

I fixed the problem with adding 
`tmp.close()`
on this line: https://github.com/cado-security/cloudgrep/blob/main/cloudgrep/cloud.py#L130

I am not sure if this is a good solution and if it won't cause problems for different systems, but it is working for Windows 11.

**Comment by chrisdoman** [comment]
Thanks @rafal-dudek -  Think we'll need to look into this one a bit more. Closing the file there might stop the read, we'll need to reproduce on win11
